log:
  level: info
  format: text

rest:
  port: 8001

db:
  dsn: "host=localhost user=matchlog password=supersecret dbname=matchlog port=3307 sslmode=disable TimeZone=Europe/Berlin"

authentication:
  secret: supersecret
  issuer: MatchLog
  valid_duration: 6h
