version: '3.1'

services:
  database:
    image: mysql:8.0.23
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'matchlogger'
      MYSQL_USER: 'guest'
      MYSQL_PASSWORD: 'secret'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - 3306:3306
