version: '3.1'

services:
  database:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: 'matchlog'
      MYSQL_USER: 'matchlog'
      MYSQL_PASSWORD: 'supersecret'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - 3307:3306