// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package rating is a generated GoMock package.
package rating

import (
	context "context"
	team "foosball/internal/team"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// UpdateRatings mocks base method.
func (m *MockService) UpdateRatings(ctx context.Context, winners, losers *team.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRatings", ctx, winners, losers)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRatings indicates an expected call of UpdateRatings.
func (mr *MockServiceMockRecorder) UpdateRatings(ctx, winners, losers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRatings", reflect.TypeOf((*MockService)(nil).UpdateRatings), ctx, winners, losers)
}
