// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package player is a generated GoMock package.
package player

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreatePlayer mocks base method.
func (m *MockRepository) CreatePlayer(ctx context.Context, player *Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlayer", ctx, player)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePlayer indicates an expected call of CreatePlayer.
func (mr *MockRepositoryMockRecorder) CreatePlayer(ctx, player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlayer", reflect.TypeOf((*MockRepository)(nil).CreatePlayer), ctx, player)
}

// DeletePlayer mocks base method.
func (m *MockRepository) DeletePlayer(ctx context.Context, player *Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlayer", ctx, player)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlayer indicates an expected call of DeletePlayer.
func (mr *MockRepositoryMockRecorder) DeletePlayer(ctx, player interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlayer", reflect.TypeOf((*MockRepository)(nil).DeletePlayer), ctx, player)
}

// GetPlayer mocks base method.
func (m *MockRepository) GetPlayer(ctx context.Context, id uint) (*Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayer", ctx, id)
	ret0, _ := ret[0].(*Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayer indicates an expected call of GetPlayer.
func (mr *MockRepositoryMockRecorder) GetPlayer(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayer", reflect.TypeOf((*MockRepository)(nil).GetPlayer), ctx, id)
}

// GetPlayers mocks base method.
func (m *MockRepository) GetPlayers(ctx context.Context, ids []uint) ([]*Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayers", ctx, ids)
	ret0, _ := ret[0].([]*Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayers indicates an expected call of GetPlayers.
func (mr *MockRepositoryMockRecorder) GetPlayers(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayers", reflect.TypeOf((*MockRepository)(nil).GetPlayers), ctx, ids)
}

// GetTopPlayersByRating mocks base method.
func (m *MockRepository) GetTopPlayersByRating(ctx context.Context, top int) ([]*Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopPlayersByRating", ctx, top)
	ret0, _ := ret[0].([]*Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopPlayersByRating indicates an expected call of GetTopPlayersByRating.
func (mr *MockRepositoryMockRecorder) GetTopPlayersByRating(ctx, top interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopPlayersByRating", reflect.TypeOf((*MockRepository)(nil).GetTopPlayersByRating), ctx, top)
}

// UpdatePlayers mocks base method.
func (m *MockRepository) UpdatePlayers(ctx context.Context, playesr []*Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlayers", ctx, playesr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlayers indicates an expected call of UpdatePlayers.
func (mr *MockRepositoryMockRecorder) UpdatePlayers(ctx, playesr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlayers", reflect.TypeOf((*MockRepository)(nil).UpdatePlayers), ctx, playesr)
}
