openapi: 3.0.3
info:
  title: foosball
  description: |-
    This service is used for logging, organizing and ranking players playing foosball.

    Ideal for an office setting.
  contact:
    email: seb@4xs.dk
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  version: 0.0.1

tags:
  - name: player
    description: Endpoints for managing players
  - name: team
    description: Endpoints for managing teams
  - name: match
    description: Endpoints for managing matches
  - name: season
    description: Endpoints for managing seasons
  - name: leaderboard
    description: Endpoints for managing leaderboards

paths:
  /player/{id}:
    get:
      tags:
        - player
      summary: Get an existing player
      description: Get an existing player by ID
      operationId: getPlayer
      parameters:
        - in: path
          name: id
          description: ID of player to fetch
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Player"
        "400":
          description: Invalid ID supplied
        "404":
          description: Player not found
        "405":
          description: Validation exception

components:
  schemas:
    Player:
      required:
        - name
        - rating
      type: object
      properties:
        id:
          type: integer
          example: 10
        name:
          type: string
          example: John Doe
        rating:
          type: integer
          example: 1000
  requestBodies:
    Player:
      description: Player object
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Player"
    PlayerArray:
      description: List of Player object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Player"
